name: pasame-la-foto

services:
  pasame-la-foto:
    build: .
    image: pasame-la-foto
    container_name: pasame-la-foto
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
